jetty:
  staticResourceBase: "classpath:static"
  connectors:
  - host: 127.0.0.1
    port: 9999

jersey:
  urlPattern: "/ui/*"

mvc:
  templateBase: "classpath:"

log:
  appenders:
    - type: console
      name: STDOUT
      target: stderr
      logFormat: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
      filters:
        - type: threshold
          level: info

    - type: file
      name: FILE
      logFormat: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
      file: logs.log
      append: false

    - type: custom
      name: multiAppender
      className: io.bootique.tools.release.service.logger.MultiAppender
      filters:
        - type: threshold
          level: debug
        - type: custom
          className: io.bootique.tools.release.service.logger.FileLoggerFilter

  appenderRefs:
    - STDOUT
    - FILE
    - multiAppender

  loggers:
    io.bootique.jersey.client.instrumented.ClientTimingFilter:
      level: error

preferences:
  organizationName: bootique
  organizationGroupId: io.bootique
  bintrayOrganizationName: bootique

jerseyclient:
  targets:
    bintray:
      url: "https://api.bintray.com"
      auth: bintray
    mvncentral:
      url: "http://search.maven.org"
    github:
      url: "https://api.github.com"

scheduler:
  threadPoolSize: 3
  triggers:
  - job: query
    initialDelay: 300ms
    # run every 5 minutes
    fixedDelay: 300000ms